output "hosts" {
  description = "Allocated CTID, IP and FQDN per host."
  value = {
    for name, _ in local.hosts : name => {
      ctid = local.ctids[name]
      ip   = local.ips[name]
      fqdn = local.fqdns[name]
    }
  }
}

output "dns_host" {
  description = "The internal resolver -- first in host_order, so its address is predictable."
  value = {
    ctid = local.ctids["dns"]
    ip   = local.dns_ip
    fqdn = "dns.${var.internal_zone}"
  }
}

output "vpn_gateway" {
  description = "The VPN gateway VM. Created by 01-setup-vpn-gateway.sh, registered in DNS here."
  value = {
    ctid = local.vpn_gateway_ctid
    ip   = local.vpn_gateway_ip
    fqdn = "vpn-gateway.${var.internal_zone}"
  }
}

# The bash bootstrap scripts need exactly one address to get started: the
# resolver's. Everything after that is addressed by name. Write it where
# lib/common.sh can source it.
resource "local_file" "bootstrap_env" {
  filename        = "${path.module}/../homelab/bootstrap/lib/terraform.env"
  file_permission = "0644"

  content = <<-EOT
    # Generated by terraform -- do not edit.
    # Sourced by lib/common.sh so the bootstrap scripts agree with the
    # provisioned inventory. Only the resolver's IP appears here; every other
    # host is reached by name through it.
    INTERNAL_ZONE="${var.internal_zone}"
    DNS_IP="${local.dns_ip}"
    DNS_CTID="${local.ctids["dns"]}"
    ROUTER_GW="${var.router_gw}"
  EOT
}
